<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Robin_Banner::css/jquery.bxslider.css') ?>"/>

<ul class="bxslider">
    <?php
    $data = $this->getData('banners');
    $auto = $this->getData('auto') ? "true" : "false";
    $speed = intval($this->getData('speed'));
    foreach ($data as $d) {
        ?>
        <li>
            <a href="<?php echo $d['link'] ?>">
                <img src="<?php echo $this->getData('mediaURL') . $d['image']; ?>"/>
            </a>
        </li>
        <?php
    }
    ?>
</ul>

<script>
    require(['jquery', 'bxslider'], function ($) {
        $(function () {
            $('.bxslider').bxSlider({
                auto: <?php echo $auto ?>,
                speed: <?php echo $speed ?>
            });
        });
    });
</script>
<?php
//$data = $this->getData('banners');
//$mediaURL = $this->getData('mediaURL');
//$auto = $this->getData('auto');
//$speed = $this->getData('speed');
//?>
<!--<ul>-->
<!--    --><?php
//        foreach ($data as $dat)
//        {
//    ?>
<!--            <li>-->
<!--                <a href="--><?php //echo $dat['link'];?><!--">-->
<!--                    <img src="--><?php //echo $mediaURL . $dat['image'];?><!--"/>-->
<!--                </a>-->
<!--            </li>-->
<!--    --><?php
//        }
//    ?>
<!---->
<!--</ul>-->
